//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VTS.rc
//
#define ID_NEWNAME                      3
#define ID_DELETENAME                   4
#define ID_IMPORTNAMES                  5
#define ID_EXPORTNAMES                  6
#define IDD_ABOUTBOX                    100
#define ID_LNCOLINDEX                   101
#define IDD_NAMES                       102
#define IDC_LINENUMBER                  103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_VTSTYPE                     129
#define IDR_VDBTYPE                     130
#define IDR_SUMMARYTYPE                 132
#define IDC_CURSOR1                     135
#define IDC_CURSOR2                     136
#define IDB_PACKETTREE                  140
#define IDD_PORT                        141
#define IDB_PORTSTATUS                  141
#define IDD_SENDIP                      142
#define IDD_SENDRAW                     144
#define IDD_SENDNPCI                    145
#define IDD_SENDNULL                    146
#define IDD_SENDVENDORNPDU              147
#define IDD_SENDWHOISRTN                148
#define IDD_SENDENET                    149
#define IDD_SENDIAMRTN                  150
#define IDD_SENDBVLCRESULT              151
#define IDD_SENDWRITEBDT                152
#define IDD_SENDREADBDT                 153
#define IDD_SENDREADBDTACK              154
#define IDD_SENDREGISTERFD              155
#define IDD_SENDREADFDT                 156
#define IDD_SENDREADFDTACK              157
#define IDD_SENDDELETEFDTENTRY          158
#define IDD_SENDBVLCI                   159
#define IDD_SENDTEST                    160
#define IDD_SENDICOULDBERTN             161
#define IDD_SENDREJECTMTN               162
#define IDD_SENDROUTERBUSY              163
#define IDD_SENDROUTERAVAIL             164
#define IDD_SENDINITRT                  165
#define IDD_SENDINITRTACK               166
#define IDD_SENDESTABLISHCTN            167
#define IDD_SENDDISCONNECTCTN           168
#define IDD_SENDSIMPLEACK               169
#define IDD_SENDSEGMENTACK              170
#define IDD_SENDERROR                   171
#define IDD_SENDREJECT                  172
#define IDD_SENDABORT                   173
#define IDD_SENDCHANGELISTERROR         174
#define IDD_SENDIAM                     175
#define IDD_SENDWHOIS                   176
#define IDD_SENDCREATEOBJECTERROR       177
#define IDD_SENDWRITEPROPMULTERROR      178
#define IDD_SENDVTCLOSEERROR            179
#define IDD_SENDIHAVE                   180
#define IDD_SENDWHOHAS                  181
#define IDD_SENDTIMESYNC                182
#define IDD_SENDUNCONFTEXTMSG           183
#define IDD_SENDCONFTEXTMSG             184
#define IDD_SENDCONFREQUEST             185
#define IDD_SENDCOMPLEXACK              186
#define IDD_SENDDEVICECOMMCTRL          187
#define IDD_SENDREINITDEVICE            188
#define IDD_ANY                         189
#define IDD_SENDREADPROP                190
#define IDD_SENDREADPROPACK             191
#define IDD_SENDWRITEPROP               192
#define IDD_SENDWRITEPROPMULT           193
#define IDD_SENDREADPROPMULT            194
#define IDD_SENDREADPROPMULTACK         195
#define IDD_SENDREADFILE                196
#define IDD_SENDREADFILEACK             197
#define IDD_SENDWRITEFILE               198
#define IDD_SENDWRITEFILEACK            199
#define IDD_SENDVTOPEN                  200
#define IDD_SENDVTOPENACK               201
#define IDD_SENDVTCLOSE                 202
#define IDD_SENDVTDATA                  203
#define IDD_SENDVTDATAACK               204
#define IDD_SENDADDLISTELEMENT          205
#define IDD_SENDCREATEOBJECT            206
#define IDD_SENDCREATEOBJECTACK         207
#define IDD_SENDDELETEOBJECT            208
#define IDD_SENDREMOVELISTELEMENT       209
#define IDD_TIMESTAMP                   210
#define IDD_SENDACKALARM                211
#define IDD_SENDCONFCOVNOTIFICATION     212
#define IDD_SENDGETALARMSUMMARY         213
#define IDD_SENDGETALARMSUMMARYACK      214
#define IDD_SENDCONFEVENTNOTIFICATION   215
#define IDD_NOTIFY_BITSTRING            216
#define IDD_NOTIFY_STATE                217
#define IDD_NOTIFY_VALUE                218
#define IDD_NOTIFY_CMDFAILURE           219
#define IDD_NOTIFY_FLOATLIMIT           220
#define IDD_NOTIFY_OUTOFRANGE           221
#define IDD_NOTIFY_COMPLEX              222
#define IDD_SENDGETENROLLMENTSUMMARY    223
#define IDD_RECIPIENTPROCESS            224
#define IDD_SENDGETENROLLMENTSUMMARYACK 225
#define IDD_SENDSUBSCRIBECOV            226
#define IDD_SENDUNCONFEVENTNOTIFICATION 227
#define IDD_SENDUNCONFCOVNOTIFICATION   228
#define IDD_PORT_ENET                   229
#define IDD_PORT_IP                     230
#define IDB_PARMSTATUS                  230
#define IDD_PORT_ARCNET                 231
#define IDD_PORT_MSTP                   232
#define IDD_PORT_PTP                    233
#define IDD_SCRIPTPARMUPDATE            234
#define IDB_CONTENTSTATUS               235
#define IDD_SELECT_SESSION              236
#define IDD_OBJID                       237
#define IDD_SCRIPTLOADRESULTS           238
#define IDD_DEVICES                     239
#define IDD_SENDREADRANGE               240
#define IDD_SENDUTCTIMESYNC             241
#define IDD_GOTOLINE                    242
#define IDD_STATISTICS                  243
#define IDD_STATISTICS_OPTIONS          244
#define IDC_PORTLIST                    1000
#define IDC_NAMELIST                    1000
#define IDC_NEWPORT                     1001
#define IDC_NAME                        1001
#define IDC_PORTTYPE                    1002
#define IDC_REMOVEDNET                  1002
#define IDC_NULLADDR                    1002
#define IDC_PORTNAME                    1003
#define IDC_REMOVEPROP                  1003
#define IDC_LOCALBROADCAST              1003
#define IDC_LOCALSTATION                1004
#define IDC_REMOTEBROADCAST             1005
#define IDC_NULLPORT                    1006
#define IDC_REMOTESTATION               1006
#define IDC_IPPORT                      1007
#define IDC_GLOBALBROADCAST             1007
#define IDC_ETHERNETPORT                1008
#define IDC_NETWORK                     1008
#define IDC_ARCNETPORT                  1009
#define IDC_ADDRESS                     1009
#define IDC_MSTPPORT                    1010
#define IDC_PTPPORT                     1011
#define IDC_ENABLEPORT                  1012
#define IDC_DADR                        1013
#define IDC_NETWORK2                    1013
#define IDC_SADR                        1015
#define IDC_MAXAPDUSIZE                 1015
#define IDC_DATA                        1016
#define IDC_ENUMERATED                  1016
#define IDC_NEXTINVOKEID                1016
#define IDC_UNSIGNED                    1017
#define IDC_APDUTIMEOUT                 1017
#define IDC_INTEGER                     1018
#define IDC_APDUSEGTIMEOUT              1018
#define IDC_REAL                        1019
#define IDC_APDURETRIES                 1019
#define IDC_VERSION                     1020
#define IDC_DOUBLE                      1020
#define IDC_DNET                        1021
#define IDC_CHARSTR                     1021
#define IDC_PRIORITY                    1022
#define IDC_VENDORID                    1022
#define IDC_OCTETSTR                    1022
#define IDC_PERFINDX                    1022
#define IDC_PORTID                      1022
#define IDC_VALUE                       1022
#define IDC_HOPCOUNT                    1023
#define IDC_BITSTR                      1023
#define IDC_PORTINFO                    1023
#define IDC_FEEDBACKVALUE               1023
#define IDC_SNET                        1024
#define IDC_OBJID                       1024
#define IDC_DATE                        1025
#define IDC_DESTPRESENT                 1026
#define IDC_TIME                        1026
#define IDC_SRCPRESENT                  1027
#define IDC_MSGTYPE                     1027
#define IDC_EXPECTINGREPLY              1028
#define IDC_DNETLIST                    1028
#define IDC_ADDDNET                     1029
#define IDC_SEGRESPONSE                 1029
#define IDC_BDTLIST                     1030
#define IDC_PROPLIST                    1030
#define IDC_ADDBDT                      1031
#define IDC_ADDPROP                     1031
#define IDC_REMOVEBDT                   1032
#define IDC_TTL                         1033
#define IDC_ADDR                        1034
#define IDC_TREMAIN                     1034
#define IDC_NONE                        1035
#define IDC_DBTN                        1036
#define IDC_RESULT                      1036
#define IDC_UNICAST                     1037
#define IDC_BROADCAST                   1038
#define IDC_FORWARD                     1039
#define IDC_OADR                        1040
#define IDC_BDTENTRY                    1041
#define IDC_BOOLEANCHECK                1042
#define IDC_ENUMERATEDCOMBO             1043
#define IDC_BOOLEAN                     1045
#define IDC_ADDFDT                      1046
#define IDC_REMOVEFDT                   1047
#define IDC_FDTLIST                     1048
#define IDC_FDTENTRY                    1049
#define IDC_REASON                      1050
#define IDC_TERMTIME                    1051
#define IDC_INVOKEID                    1052
#define IDC_SERVICECOMBO                1053
#define IDC_NAK                         1054
#define IDC_ERRORCLASSCOMBO             1054
#define IDC_DTDATE                      1054
#define IDC_CLIENT                      1055
#define IDC_ERRORCODECOMBO              1055
#define IDC_DTTIME                      1055
#define IDC_SERVER                      1056
#define IDC_ELEMENT                     1056
#define IDC_SEQNUM                      1057
#define IDC_PROPERTYID                  1057
#define IDC_WINDOWSIZE                  1058
#define IDC_INDEX                       1058
#define IDC_REJECTCOMBO                 1059
#define IDC_ABORTCOMBO                  1060
#define IDC_DEVICEID                    1061
#define IDC_MAXAPDULENGTH               1062
#define IDC_SEGMENTATIONCOMBO           1063
#define IDC_HIGHLIMIT                   1063
#define IDC_LOWLIMIT                    1064
#define IDC_OBJECTID                    1065
#define IDC_ADDID                       1066
#define IDC_REMOVEID                    1067
#define IDC_IDLIST                      1068
#define IDC_TIMEREMAINING               1068
#define IDC_ID                          1069
#define IDC_OBJECTNAME                  1070
#define IDC_AUTOSYNC                    1071
#define IDC_MSG                         1071
#define IDC_SOURCEDEVICE                1072
#define IDC_CHARCLASS                   1073
#define IDC_NUMCLASS                    1074
#define IDC_NORMAL                      1075
#define IDC_URGENT                      1076
#define IDC_SEGMENTED                   1076
#define IDC_MOREFOLLOWS                 1077
#define IDC_SEQNUMBER                   1078
#define IDC_SEGCOUNTMSG                 1080
#define IDC_SEGMENTSIZE                 1081
#define IDC_ENABLE                      1081
#define IDC_DISABLE                     1082
#define IDC_TIMEDURATION                1083
#define IDC_PASSWORD                    1084
#define IDC_COLDSTART                   1085
#define IDC_WARMSTART                   1086
#define IDC_CONTEXT                     1087
#define IDC_ELEMLIST                    1088
#define IDC_VENDOR                      1088
#define IDC_ADDELEM                     1089
#define IDC_ENCODED                     1089
#define IDC_REMOVEELEM                  1090
#define IDC_TYPECOMBO                   1091
#define IDC_ANY                         1092
#define IDC_PROPCOMBO                   1094
#define IDC_ARRAYINDEX                  1095
#define IDC_VALUECOMBO                  1095
#define IDC_PRIORITYX                   1096
#define IDC_ISSUECONFIRMED              1096
#define IDC_OBJLIST                     1097
#define IDC_STARTRECORD                 1097
#define IDC_OBJECTTYPECOMBO             1097
#define IDC_LIFETIME                    1097
#define IDC_ADDOBJ                      1098
#define IDC_RECORDCOUNT                 1098
#define IDC_MACADDRESS                  1098
#define IDC_REMOVEOBJ                   1099
#define IDC_FILEID                      1100
#define IDC_OBJUP                       1100
#define IDC_STARTPOSITION               1101
#define IDC_OBJDOWN                     1101
#define IDC_OCTETCOUNT                  1102
#define IDC_PROPUP                      1102
#define IDC_ADDRECORD                   1103
#define IDC_PROPDOWN                    1103
#define IDC_REMOVERECORD                1104
#define IDC_RECORDLIST                  1105
#define IDC_RECORDDATA                  1106
#define IDC_EOF                         1107
#define IDC_PORTCOMBO                   1108
#define IDC_VTCLASSCOMBO                1109
#define IDC_SESSIONID                   1110
#define IDC_DATAFLAG                    1111
#define IDC_ALLDATAFLAG                 1112
#define IDC_ACCEPTEDCOUNT               1113
#define IDC_ACKPROCESSID                1114
#define IDC_ACKSOURCE                   1115
#define IDC_NOTIFYCLASS                 1116
#define IDC_EVENTSTATECOMBO             1117
#define IDC_TIMESTAMP                   1118
#define IDC_TIMEOFACK                   1119
#define IDC_PROCESSID                   1119
#define IDC_TOOFFNORMAL                 1120
#define IDC_TOFAULT                     1121
#define IDC_NOTIFYTYPECOMBO             1121
#define IDC_EVENTTYPECOMBO              1121
#define IDC_TONORMAL                    1122
#define IDC_FROMSTATECOMBO              1122
#define IDC_ADDSUMELEM                  1123
#define IDC_TOSTATECOMBO                1123
#define IDC_REMOVESUMELEM               1124
#define IDC_EVENTVALUES                 1124
#define IDC_ALARMSUMLIST                1125
#define IDC_ACKREQUIRED                 1126
#define IDC_MESSAGETEXT                 1128
#define IDC_REFBITSTRING                1129
#define IDC_INALARM                     1130
#define IDC_FAULT                       1131
#define IDC_OVERRIDDEN                  1132
#define IDC_OUTOFSERVICE                1133
#define IDC_CHANGEDVALUE                1134
#define IDC_SETPOINTVALUE               1134
#define IDC_CHANGEDBITS                 1135
#define IDC_ERRORLIMIT                  1135
#define IDC_COMMANDVALUE                1137
#define IDC_REFVALUE                    1138
#define IDC_EXCEEDINGVALUE              1139
#define IDC_DEADBAND                    1140
#define IDC_EXCEEDINGLIMIT              1141
#define IDC_ACKFILTERCOMBO              1142
#define IDC_MINPRIORITY                 1143
#define IDC_MAXPRIORITY                 1144
#define IDC_NOTIFICATIONCLASS           1145
#define IDC_RECIPIENTPROCESS            1146
#define IDC_ENROLLMENTSUMLIST           1147
#define IDC_CONFIG                      1148
#define IDC_SOCKET                      1149
#define IDC_COLOR                       1149
#define IDC_ADAPTERCOMBO                1150
#define IDC_PROMISCUOUS                 1151
#define IDC_PARMNAME                    1152
#define IDC_PARMDESC                    1153
#define IDC_PARMSCRIPTVALUE             1154
#define IDC_PARMVALUE                   1155
#define IDC_PARMERRMSG                  1156
#define IDC_DOCLIST                     1157
#define IDC_DEVICEIDBTN                 1158
#define IDC_RESERVED                    1159
#define IDC_INSTANCE                    1160
#define IDC_OBJTYPECOMBO                1161
#define IDC_VALUEIDBTN                  1162
#define IDC_OBJIDBTN                    1163
#define IDC_OBJECTIDBTN                 1164
#define IDC_SOURCEDEVICEBTN             1165
#define IDC_FILEIDBTN                   1166
#define IDC_SADRCOMBO                   1167
#define IDC_DADRCOMBO                   1168
#define IDC_OADRCOMBO                   1169
#define IDC_ADDRCOMBO                   1170
#define IDC_MAXAPDULEN                  1171
#define IDC_VENDORNAME                  1172
#define IDC_PRODUCTNAME                 1173
#define IDC_DEVICECOMBO                 1173
#define IDC_PRODUCTMODELNUMBER          1174
#define IDC_ROUTER                      1174
#define IDC_PRODUCTDESCRIPTION          1175
#define IDC_SEGTYPE                     1175
#define IDC_SEGBOTH                     1176
#define IDC_SEGTRANSMIT                 1177
#define IDC_SEGRECEIVE                  1178
#define IDC_RAW                         1178
#define IDC_SEGNONE                     1179
#define IDC_BTR                         1179
#define IDC_DEVICELIST                  1180
#define IDC_BBMD                        1180
#define IDC_NEWDEVICE                   1181
#define IDC_BIP                         1181
#define IDC_IAM                         1182
#define IDC_FOREIGN                     1182
#define IDC_SEGSIZE                     1183
#define ID_BBMDPEERS                    1183
#define ID_BTRPEERS                     1184
#define IDC_HOSTADDR                    1185
#define IDC_STARTDATUM                  1190
#define IDC_ENDDATUM                    1191
#define IDC_COUNT                       1192
#define IDC_REFINDEX                    1193
#define IDC_RADIONONE                   1195
#define IDC_RADIOPOSITION               1196
#define IDC_RADIOTIME                   1197
#define IDC_RADIOTIMERANGE              1198
#define IDC_TIMESTART                   1199
#define IDC_ENDTIME                     1200
#define IDC_BEGDATECAPTION              1201
#define IDC_AUTOSYNCTIME                1202
#define IDC_DAYLIGHTSAVINGS             1203
#define IDC_UTCDATE                     1204
#define IDC_UTCTIME                     1205
#define IDC_UTCOFFSET                   1206
#define IDC_STATICUTCDATE               1207
#define IDC_STATICUTCTIME               1208
#define IDC_STATICUTCOFFSET             1209
#define IDC_STATICUTCTIMEFMT            1211
#define IDC_STATICUTCRANGE              1212
#define IDC_EDIT_LINEINDEX              1213
#define IDC_PORT                        1213
#define IDC_BDTPORT                     1213
#define IDC_TOTALSENT                   1213
#define IDC_TOTALSEND                   1213
#define IDC_IP                          1214
#define IDC_TOTALRECEIVE                1214
#define IDC_MASK                        1215
#define IDC_SENDRATE                    1215
#define IDC_IPSEND                      1215
#define IDC_RECEIVERATE                 1216
#define IDC_IPRECEIVE                   1216
#define IDC_ETHERNETSEND                1217
#define IDC_ALARMANDEVENT               1218
#define IDC_ETHERNETRECEIVE             1218
#define IDC_FILEACCESS                  1219
#define IDC_OBJECTACCESS                1220
#define IDC_DETAIL                      1221
#define IDC_ARCNETSEND                  1221
#define IDC_ARCNETRECEIVE               1222
#define IDC_IP_SEND                     1223
#define IDC_IP_SEND_CHECK               1223
#define IDC_MSTPSEND                    1223
#define IDC_ETHERNET_SEND               1224
#define IDC_MSTPRECEIVE                 1224
#define IDC_SERVICE_TREE                1225
#define IDC_PACKET_TYPE                 1226
#define IDC_PTPSEND                     1226
#define IDC_PTPRECEIVE                  1227
#define IDC_ARCNET_SEND                 1228
#define IDC_REMOTEDEVICEMANAGEMENT      1229
#define IDC_IP_RECEIVE_CHECK            1229
#define IDC_PACKET_TYPE_TEXT            1229
#define IDC_VIRTUALTERMINAL             1230
#define IDC_MSTP_SEND                   1230
#define IDC_ETHERNET_SEND_CHECK         1230
#define IDC_ACK                         1231
#define IDC_ETHERNET_RECEIVE_CHECK      1231
#define IDC_ERRORS                      1232
#define IDC_ARCNET_SEND_CHECK           1232
#define IDC_PTP_SEND                    1233
#define IDC_ARCNET_RECEIVE_CHECK        1233
#define IDC_OVERALL_SEND                1234
#define IDC_MSTP_SEND_CHECK             1234
#define IDC_IP_RECEIVE                  1235
#define IDC_MSTP_RECEIVE_CHECK          1235
#define IDC_ETHERNET_RECEIVE            1236
#define IDC_PTP_RECEIVE_CHECK           1236
#define IDC_ARCNET_RECEIVE              1237
#define IDC_PTP_SEND_CHECK              1237
#define IDC_MSTP_RECEIVE                1238
#define IDC_OVERALL_SEND_CHECK          1238
#define IDC_PTP_RECEIVE                 1239
#define IDC_OVERALL_RECEIVE_CHECK       1239
#define IDC_OVERALL_RECEIVE             1240
#define IDC_SEL_ALL                     1240
#define IDC_CLEAR_ALL                   1241
#define IDC_RANGE_2                     1243
#define IDC_RANGE_3                     1244
#define IDC_RANGE_4                     1245
#define IDC_RANGE_5                     1246
#define IDC_OPTIONS                     1247
#define ID_VIEW_FIRSTFRAME              32771
#define ID_VIEW_PREVFRAME               32772
#define ID_VIEW_NEXTFRAME               32773
#define ID_VIEW_LASTFRAME               32774
#define ID_EDIT_PORTS                   32782
#define ID_EDIT_NAMES                   32783
#define ID_EDIT_CAPTUREFILTER           32785
#define ID_EDIT_DISPLAYFILTER           32786
#define ID_EDIT_PREFERENCES             32787
#define ID_EDIT_DELETE                  32788
#define ID_SCRIPT_CHECK_SYNTAX          32789
#define ID_SCRIPT_RUN                   32790
#define ID_SCRIPT_HALT                  32791
#define ID_SCRIPT_STEP                  32792
#define ID_SCRIPT_RESET                 32793
#define ID_SCRIPT_KILL                  32794
#define ID_SCRIPT_STEPPASS              32795
#define ID_SCRIPT_STEPFAIL              32796
#define ID_SEND_NEWPACKET               32797
#define ID_SEND_SENDAGAIN               32798
#define ID_BUTTON32799                  32799
#define ID_BUTTON32800                  32800
#define ID_SCRIPT_LOADEPICS             32801
#define ID_EDIT_DEVICES                 32803
#define IDC_EDIT_GOTOLINE               32804
#define ID_MENUITEM32806                32806
#define ID_VIEW_HEX                     32807
#define ID_VIEW_DETAIL                  32808
#define ID_VIEW_STATISTICS              32809
#define ID_FILE_EXPORT                  32810

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        245
#define _APS_NEXT_COMMAND_VALUE         32811
#define _APS_NEXT_CONTROL_VALUE         1248
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
