//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VTS.rc
//
#define ID_NEWNAME                      3
#define IDC_DEVIMPORT                   3
#define ID_APPLY                        3
#define IDC_RESET                       3
#define ID_DELETENAME                   4
#define IDC_DEVEXPORT                   4
#define ID_IMPORTNAMES                  5
#define ID_EXPORTNAMES                  6
#define IDD_ABOUTBOX                    100
#define ID_LNCOLINDEX                   101
#define IDD_NAMES                       102
#define IDC_LINENUMBER                  103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_VTSTYPE                     129
#define IDR_VDBTYPE                     130
#define IDR_SUMMARYTYPE                 132
#define IDR_DEVTREE                     133
#define IDC_CURSOR1                     135
#define IDC_CURSOR2                     136
#define IDB_PACKETTREE                  140
#define IDD_PORT                        141
#define IDB_PORTSTATUS                  141
#define IDD_SENDIP                      142
#define IDD_SENDRAW                     144
#define IDD_SENDNPCI                    145
#define IDD_SENDNULL                    146
#define IDD_SENDVENDORNPDU              147
#define IDD_SENDWHOISRTN                148
#define IDD_SENDENET                    149
#define IDD_SENDIAMRTN                  150
#define IDD_SENDBVLCRESULT              151
#define IDD_SENDWRITEBDT                152
#define IDD_SENDREADBDT                 153
#define IDD_SENDREADBDTACK              154
#define IDD_SENDREGISTERFD              155
#define IDD_SENDREADFDT                 156
#define IDD_SENDREADFDTACK              157
#define IDD_SENDDELETEFDTENTRY          158
#define IDD_SENDBVLCI                   159
#define IDD_SENDTEST                    160
#define IDD_SENDICOULDBERTN             161
#define IDD_SENDREJECTMTN               162
#define IDD_SENDROUTERBUSY              163
#define IDD_SENDROUTERAVAIL             164
#define IDD_SENDINITRT                  165
#define IDD_SENDINITRTACK               166
#define IDD_SENDESTABLISHCTN            167
#define IDD_SENDDISCONNECTCTN           168
#define IDD_SENDSIMPLEACK               169
#define IDD_SENDSEGMENTACK              170
#define IDD_SENDERROR                   171
#define IDD_SENDREJECT                  172
#define IDD_SENDABORT                   173
#define IDD_SENDCHANGELISTERROR         174
#define IDD_SENDIAM                     175
#define IDD_SENDWHOIS                   176
#define IDD_SENDCREATEOBJECTERROR       177
#define IDD_SENDWRITEPROPMULTERROR      178
#define IDD_SENDVTCLOSEERROR            179
#define IDD_SENDIHAVE                   180
#define IDD_SENDWHOHAS                  181
#define IDD_SENDTIMESYNC                182
#define IDD_SENDUNCONFTEXTMSG           183
#define IDD_SENDCONFTEXTMSG             184
#define IDD_SENDCONFREQUEST             185
#define IDD_SENDCOMPLEXACK              186
#define IDD_SENDDEVICECOMMCTRL          187
#define IDD_SENDREINITDEVICE            188
#define IDD_ANY                         189
#define IDD_SENDREADPROP                190
#define IDD_SENDREADPROPACK             191
#define IDD_SENDWRITEPROP               192
#define IDD_SENDWRITEPROPMULT           193
#define IDD_SENDREADPROPMULT            194
#define IDD_SENDREADPROPMULTACK         195
#define IDD_SENDREADFILE                196
#define IDD_SENDREADFILEACK             197
#define IDD_SENDWRITEFILE               198
#define IDD_SENDWRITEFILEACK            199
#define IDD_SENDVTOPEN                  200
#define IDD_SENDVTOPENACK               201
#define IDD_SENDVTCLOSE                 202
#define IDD_SENDVTDATA                  203
#define IDD_SENDVTDATAACK               204
#define IDD_SENDADDLISTELEMENT          205
#define IDD_SENDCREATEOBJECT            206
#define IDD_SENDCREATEOBJECTACK         207
#define IDD_SENDDELETEOBJECT            208
#define IDD_SENDREMOVELISTELEMENT       209
#define IDD_TIMESTAMP                   210
#define IDD_SENDACKALARM                211
#define IDD_SENDCONFCOVNOTIFICATION     212
#define IDD_SENDGETALARMSUMMARY         213
#define IDD_SENDGETALARMSUMMARYACK      214
#define IDD_SENDCONFEVENTNOTIFICATION   215
#define IDD_NOTIFY_BITSTRING            216
#define IDD_NOTIFY_STATE                217
#define IDD_NOTIFY_VALUE                218
#define IDD_NOTIFY_CMDFAILURE           219
#define IDD_NOTIFY_FLOATLIMIT           220
#define IDD_NOTIFY_OUTOFRANGE           221
#define IDD_NOTIFY_COMPLEX              222
#define IDD_SENDGETENROLLMENTSUMMARY    223
#define IDD_RECIPIENTPROCESS            224
#define IDD_SENDGETENROLLMENTSUMMARYACK 225
#define IDD_SENDSUBSCRIBECOV            226
#define IDD_SENDUNCONFEVENTNOTIFICATION 227
#define IDD_SENDUNCONFCOVNOTIFICATION   228
#define IDD_PORT_ENET                   229
#define IDD_PORTPAGE_ENET               229
#define IDD_PORT_IP                     230
#define IDB_PARMSTATUS                  230
#define IDD_PORT_ARCNET                 231
#define IDD_PORT_MSTP                   232
#define IDD_PORT_PTP                    233
#define IDD_PORTPAGE_PTP                233
#define IDD_SCRIPTPARMUPDATE            234
#define IDB_CONTENTSTATUS               235
#define IDD_SELECT_SESSION              236
#define IDD_OBJID                       237
#define IDD_SCRIPTLOADRESULTS           238
#define IDD_DEVICES                     239
#define IDD_SENDREADRANGE               240
#define IDD_SENDUTCTIMESYNC             241
#define IDD_GOTOLINE                    242
#define IDD_STATISTICS                  243
#define IDD_STATISTICS_OPTIONS          244
#define IDD_SENDDEVICE                  245
#define IDD_DIALOG1                     246
#define IDD_DEVICESTREE                 246
#define IDD_READALLPROPSETTING          247
#define IDD_LOADEPICSCONSCHK            248
#define IDD_SCRIPTMAKE                  250
#define IDD_SCRIPTCHECK                 251
#define IDB_SCRIPTMAKE                  252
#define IDD_OBJPROPVALUE                252
#define IDB_SCRIPTCHECK                 253
#define IDD_OBJPROPLIST                 253
#define IDD_OBJPROPARRAY                254
#define IDD_PACKETFILE                  255
#define IDD_DATERANGE                   255
#define IDD_OBJPROPERTYLIST             256
#define IDD_ADDRESSBINDING              256
#define IDD_CALENDARENTTRY              257
#define IDD_TIMESTAMP_CHOICE            258
#define IDD_DEVTREENULL                 259
#define IDD_DEVTREEDEV                  260
#define IDD_DEVTREEOBJ                  261
#define IDD_DEVTREEPROP                 263
#define IDD_DEVTREEVALUE                264
#define IDD_BTYPEGENERIC                266
#define IDB_DEVTREE                     268
#define IDD_PORTPAGE_IP                 269
#define IDD_PORTPAGE_NULL               270
#define IDD_PORTPAGE_ARCNET             271
#define IDD_PORTPAGE_MSTP               272
#define IDD_PREFERENCES                 273
#define IDD_DATETIME                    274
#define IDD_TIMESTAMP1                  275
#define IDD_VENDORPROPID                276
#define IDD_SCRIPTINCLUDE               277
#define IDD_FILTERS                     278
#define IDD_LISTOF                      279
#define IDD_LISTOF_DESTINATION          279
#define IDD_DESTINATION                 280
#define IDD_SENDMSTP                    281
#define IDD_MSTPIMP_NBLINK              282
#define IDB_NBLINK                      284
#define IDD_EPICSVIEW                   285
#define IDB_EPICSTREE                   286
#define IDD_NOTIFY_BUFFERREADY          287
#define IDD_SENDGETEVENTINFO            288
#define IDD_SENDGETEVENTINFOACK         289
#define IDD_LISTOF_TIMESTAMP            291
#define IDD_LISTOF_UNSIGNED             292
#define IDD_ACTION                      294
#define IDD_ACTIONCOMMAND               295
#define IDD_ACTIONLIST                  296
#define IDD_BINARYPV                    297
#define IDD_CLIENTCOV                   298
#define IDD_DAYSOFWEEK                  299
#define IDB_BMALOGO                     300
#define IDD_DEVICESTATUS                300
#define IDB_WINPCAPLOGO                 301
#define IDD_ENGIEERINGUNITS             301
#define IDD_DEVICEOBJECTREFERENCE       302
#define IDD_DEVICEOBJECTPROPREFERENCE   303
#define IDD_RECIPIENT                   304
#define IDD_OBJECTPROPERTYREFERENCE     305
#define IDD_COVSUBSCRIPTION             306
#define IDD_EVENTSTATE                  307
#define IDD_EVENTTRANSITIONBITS         308
#define IDD_FILEACCESSMETHOD            309
#define IDD_LIFESAFETYMODE              310
#define IDD_LIFESAFETYOPERATION         311
#define IDD_LIFESAFETYSTATE             312
#define IDD_EVENTTYPE                   313
#define IDD_LIMITENABLE                 314
#define IDD_LOGSTATUS                   315
#define IDD_MAINTENANCE                 316
#define IDD_NOTIFYTYPE                  317
#define IDD_OBJECTTYPE                  318
#define IDD_POLARITY                    319
#define IDD_PROGRAMERROR                320
#define IDD_PROGRAMREQUEST              321
#define IDD_PROGRAMSTATE                322
#define IDD_PROPERTYIDENTIFIER          323
#define IDD_RELIABILITY                 324
#define IDD_SEGMENTATION                325
#define IDD_SILENCESTATE                326
#define IDD_VTCLASS                     327
#define IDD_WEEKNDAY                    328
#define IDD_VTSESSION                   329
#define IDD_TIMEVALUE                   330
#define IDD_SETPOINTREFERENCE           331
#define IDD_SESSIONKEY                  332
#define IDD_RESULTFLAGS                 333
#define IDD_PROPERTYREFERENCE           334
#define IDD_PROPERTYSTATES              335
#define IDD_OBJECTPROPERTYVALUE         336
#define IDD_PROPERTYVALUE               337
#define IDD_PRIORITYVALUE               338
#define IDD_STATUSFLAGS                 339
#define IDD_PRIORITYARRAY               340
#define IDD_LOGRECORD                   341
#define IDD_DAILYSCHEDULE               342
#define IDD_OBJECTTYPESSUPPORTED        343
#define IDD_SERVICESSUPPORTED           344
#define IDD_SPECIALEVENT                345
#define IDD_LISTOF_BITSTRING            346
#define IDD_LISTOF_LIFESAFETYSTATE      347
#define IDD_LISTOFPROPERTYSTATES        348
#define IDD_EVENT_VALUE                 349
#define IDD_EVENT_STATE                 350
#define IDD_EVENT_OUTOFRANGE            351
#define IDD_EVENT_FLOATLIMIT            352
#define IDD_EVENT_LIFESAFETY            353
#define IDD_EVENT_CMDFAILURE            354
#define IDD_EVENT_BUFFERREADY           355
#define IDD_EVENT_BITSTRING             356
#define IDD_EVENTPARAMETER              357
#define IDD_LISTOFREADACCESSRESULT      358
#define IDD_LISTOFREADACCESSSPECIFICATION 359
#define IDD_EPICSVIEW_PROP              360
#define IDR_EPICS_PROP                  361
#define IDD_BACKUP_RESTORE              362
#define IDR_GLOBALBAR                   364
#define IDD_COLOR                       365
#define IDB_COLOR                       366
#define IDR_PKTBAR                      367
#define IDR_COLUMNS                     369
#define IDR_SUMMARYWIN                  369
#define IDI_RECVPKT                     370
#define IDD_BACKUP_RESTORE_PROGRESS     371
#define IDI_SENDPKT                     371
#define IDD_EDITRESENTPKT               372
#define IDD_SENDSUBSCRIBECOVPROPERTY    373
#define IDD_DEVADV                      374
#define IDD_NOTIFY_CHG_LS               375
#define IDD_NOTIFY_EXTENDED             376
#define IDD_NOTIFY_UNS_RANGE            377
#define IDD_DEVTREEOPT                  378
#define IDD_INCONSISTENT_PARS           379
#define IDD_INCONSISTENT_PARS_PROGRESS  380
#define IDD_SELECT_TEMPLATE             381
#define IDR_SCRIPT_CONTEXT              382
#define IDC_PORTLIST                    1000
#define IDC_NAMELIST                    1000
#define IDC_NEWPORT                     1001
#define IDC_NAME                        1001
#define IDC_PORTTYPE                    1002
#define IDC_REMOVEDNET                  1002
#define IDC_NULLADDR                    1002
#define IDC_PORTNAME                    1003
#define IDC_REMOVEPROP                  1003
#define IDC_LOCALBROADCAST              1003
#define IDC_LOCALSTATION                1004
#define IDC_REMOTEBROADCAST             1005
#define IDC_NULLPORT                    1006
#define IDC_REMOTESTATION               1006
#define IDC_IPPORT                      1007
#define IDC_GLOBALBROADCAST             1007
#define IDC_ETHERNETPORT                1008
#define IDC_NETWORK                     1008
#define IDC_ARCNETPORT                  1009
#define IDC_ADDRESS                     1009
#define IDC_LOCALSESSIONID              1009
#define IDC_SESSIONKEY                  1009
#define IDC_MSTPPORT                    1010
#define IDC_ACCEPT                      1010
#define IDC_PTPPORT                     1011
#define IDC_REJECT                      1011
#define IDC_ENABLEPORT                  1012
#define IDC_DADR                        1013
#define IDC_NETWORK2                    1013
#define IDC_SADR                        1015
#define IDC_MAXAPDUSIZE                 1015
#define IDC_DATA                        1016
#define IDC_ENUMERATED                  1016
#define IDC_NEXTINVOKEID                1016
#define IDC_UNSIGNED                    1017
#define IDC_APDUTIMEOUT                 1017
#define IDC_INTEGER                     1018
#define IDC_APDUSEGTIMEOUT              1018
#define IDC_REAL                        1019
#define IDC_APDURETRIES                 1019
#define IDC_VERSION                     1020
#define IDC_DOUBLE                      1020
#define IDC_DNET                        1021
#define IDC_CHARSTR                     1021
#define IDC_PRIORITY                    1022
#define IDC_VENDORID                    1022
#define IDC_OCTETSTR                    1022
#define IDC_PERFINDX                    1022
#define IDC_PORTID                      1022
#define IDC_VALUE                       1022
#define IDC_HOPCOUNT                    1023
#define IDC_BITSTR                      1023
#define IDC_PORTINFO                    1023
#define IDC_FEEDBACKVALUE               1023
#define IDC_ARRAY                       1023
#define IDC_SNET                        1024
#define IDC_OBJID                       1024
#define IDC_DATE                        1025
#define IDC_VALUETOARRAY                1025
#define IDC_DESTPRESENT                 1026
#define IDC_TIME                        1026
#define IDC_ARRAYTOVALUE                1026
#define IDC_SRCPRESENT                  1027
#define IDC_MSGTYPE                     1027
#define IDC_PROPID                      1027
#define IDC_EXPECTINGREPLY              1028
#define IDC_DNETLIST                    1028
#define IDC_ADDDNET                     1029
#define IDC_SEGRESPONSE                 1029
#define IDC_BDTLIST                     1030
#define IDC_PROPLIST                    1030
#define IDC_ADDBDT                      1031
#define IDC_ADDPROP                     1031
#define IDC_REMOVEBDT                   1032
#define IDC_TTL                         1033
#define IDC_ADDR                        1034
#define IDC_TREMAIN                     1034
#define IDC_NONE                        1035
#define IDC_DBTN                        1036
#define IDC_RESULT                      1036
#define IDC_UNICAST                     1037
#define IDC_BROADCAST                   1038
#define IDC_FORWARD                     1039
#define IDC_OADR                        1040
#define IDC_BDTENTRY                    1041
#define IDC_BOOLEANCHECK                1042
#define IDC_ENUMERATEDCOMBO             1043
#define IDC_BOOLEAN                     1045
#define IDC_ADDFDT                      1046
#define IDC_REMOVEFDT                   1047
#define IDC_FDTLIST                     1048
#define IDC_FDTENTRY                    1049
#define IDC_REASON                      1050
#define IDC_TERMTIME                    1051
#define IDC_INVOKEID                    1052
#define IDC_SERVICECOMBO                1053
#define IDC_NAK                         1054
#define IDC_ERRORCLASSCOMBO             1054
#define IDC_DTDATE                      1054
#define IDC_CLIENT                      1055
#define IDC_ERRORCODECOMBO              1055
#define IDC_DTTIME                      1055
#define IDC_SERVER                      1056
#define IDC_ELEMENT                     1056
#define IDC_SEQNUM                      1057
#define IDC_PROPERTYID                  1057
#define IDC_WINDOWSIZE                  1058
#define IDC_INDEX                       1058
#define IDC_REJECTCOMBO                 1059
#define IDC_ABORTCOMBO                  1060
#define IDC_DEVICEID                    1061
#define IDC_MAXAPDULENGTH               1062
#define IDC_SEGMENTATIONCOMBO           1063
#define IDC_HIGHLIMIT                   1063
#define IDC_LOWLIMIT                    1064
#define IDC_OBJECTID                    1065
#define IDC_MOREITEM                    1065
#define IDC_ADDID                       1066
#define IDC_REMOVEID                    1067
#define IDC_IDLIST                      1068
#define IDC_TIMEREMAINING               1068
#define IDC_ID                          1069
#define IDC_OBJECTNAME                  1070
#define IDC_AUTOSYNC                    1071
#define IDC_MSG                         1071
#define IDC_SOURCEDEVICE                1072
#define IDC_CHARCLASS                   1073
#define IDC_NUMCLASS                    1074
#define IDC_NORMAL                      1075
#define IDC_URGENT                      1076
#define IDC_SEGMENTED                   1076
#define IDC_MOREFOLLOWS                 1077
#define IDC_SEQNUMBER                   1078
#define IDC_SEGCOUNTMSG                 1080
#define IDC_SEGMENTSIZE                 1081
#define IDC_ENABLE                      1081
#define IDC_DISABLE                     1082
#define IDC_TIMEDURATION                1083
#define IDC_PASSWORD                    1084
#define IDC_COLDSTART                   1085
#define IDC_DISABLE_INIT                1085
#define IDC_WARMSTART                   1086
#define IDC_CONTEXT                     1087
#define IDC_ELEMLIST                    1088
#define IDC_VENDOR                      1088
#define IDC_ADDELEM                     1089
#define IDC_ENCODED                     1089
#define IDC_REMOVEELEM                  1090
#define IDC_TYPECOMBO                   1091
#define IDC_ANY                         1092
#define IDC_PROPCOMBO                   1094
#define IDC_ARRAYINDEX                  1095
#define IDC_VALUECOMBO                  1095
#define IDC_LS_MODE                     1095
#define IDC_PRIORITYX                   1096
#define IDC_ISSUECONFIRMED              1096
#define IDC_PRIO                        1096
#define IDC_PROPVALUE_PRIORITY          1096
#define IDC_LS_OPERATION                1096
#define IDC_OBJLIST                     1097
#define IDC_STARTRECORD                 1097
#define IDC_OBJECTTYPECOMBO             1097
#define IDC_LIFETIME                    1097
#define IDC_POSTDELAY                   1097
#define IDC_ADDOBJ                      1098
#define IDC_RECORDCOUNT                 1098
#define IDC_MACADDRESS                  1098
#define IDC_REMOVEOBJ                   1099
#define IDC_REMOTESESSIONID             1099
#define IDC_FILEID                      1100
#define IDC_OBJUP                       1100
#define IDC_STARTPOSITION               1101
#define IDC_OBJDOWN                     1101
#define IDC_OCTETCOUNT                  1102
#define IDC_PROPUP                      1102
#define IDC_ADDRECORD                   1103
#define IDC_PROPDOWN                    1103
#define IDC_REMOVERECORD                1104
#define IDC_RECORDLIST                  1105
#define IDC_RECORDDATA                  1106
#define IDC_EOF                         1107
#define IDC_PORTCOMBO                   1108
#define IDC_VTCLASSCOMBO                1109
#define IDC_FNGROUPCOMBO                1109
#define IDC_SESSIONID                   1110
#define IDC_DATAFLAG                    1111
#define IDC_ADDRTYPECOMBO               1111
#define IDC_ALLDATAFLAG                 1112
#define IDC_ACCEPTEDCOUNT               1113
#define IDC_ACKPROCESSID                1114
#define IDC_ACKSOURCE                   1115
#define IDC_NOTIFYCLASS                 1116
#define IDC_EVENTSTATECOMBO             1117
#define IDC_TIMESTAMP                   1118
#define IDC_TIMEOFACK                   1119
#define IDC_PROCESSID                   1119
#define IDC_TOOFFNORMAL                 1120
#define IDC_TOFAULT                     1121
#define IDC_NOTIFYTYPECOMBO             1121
#define IDC_EVENTTYPECOMBO              1121
#define IDC_TONORMAL                    1122
#define IDC_FROMSTATECOMBO              1122
#define IDC_ADDSUMELEM                  1123
#define IDC_TOSTATECOMBO                1123
#define IDC_REMOVESUMELEM               1124
#define IDC_EVENTVALUES                 1124
#define IDC_ALARMSUMLIST                1125
#define IDC_ACKREQUIRED                 1126
#define IDC_MESSAGETEXT                 1128
#define IDC_REFBITSTRING                1129
#define IDC_INALARM                     1130
#define IDC_FAULT                       1131
#define IDC_OVERRIDDEN                  1132
#define IDC_OUTOFSERVICE                1133
#define IDC_CHANGEDVALUE                1134
#define IDC_SETPOINTVALUE               1134
#define IDC_CHANGEDBITS                 1135
#define IDC_ERRORLIMIT                  1135
#define IDC_COMMANDVALUE                1137
#define IDC_REFVALUE                    1138
#define IDC_EXCEEDINGVALUE              1139
#define IDC_DEADBAND                    1140
#define IDC_EXCEEDINGLIMIT              1141
#define IDC_ACKFILTERCOMBO              1142
#define IDC_MINPRIORITY                 1143
#define IDC_MAXPRIORITY                 1144
#define IDC_NOTIFICATIONCLASS           1145
#define IDC_RECIPIENTPROCESS            1146
#define IDC_ENROLLMENTSUMLIST           1147
#define IDC_CONFIG                      1148
#define IDC_UDP_PORT                    1149
#define IDC_COLOR                       1149
#define IDC_ADAPTERCOMBO                1150
#define IDC_PROMISCUOUS                 1151
#define IDC_PARMNAME                    1152
#define IDC_PARMDESC                    1153
#define IDC_PARMSCRIPTVALUE             1154
#define IDC_PARMVALUE                   1155
#define IDC_PARMERRMSG                  1156
#define IDC_DOCLIST                     1157
#define IDC_DEVICEIDBTN                 1158
#define IDC_RESERVED                    1159
#define IDC_INSTANCE                    1160
#define IDC_OBJTYPECOMBO                1161
#define IDC_VALUEIDBTN                  1162
#define IDC_OBJIDBTN                    1163
#define IDC_OBJECTIDBTN                 1164
#define IDC_SOURCEDEVICEBTN             1165
#define IDC_FILEIDBTN                   1166
#define IDC_SADRCOMBO                   1167
#define IDC_DADRCOMBO                   1168
#define IDC_OADRCOMBO                   1169
#define IDC_ADDRCOMBO                   1170
#define IDC_MAXAPDULEN                  1171
#define IDC_VENDORNAME                  1172
#define IDC_MAX_SEGMENTS_ACCEPTED       1172
#define IDC_PRODUCTNAME                 1173
#define IDC_DEVICECOMBO                 1173
#define IDC_PRODUCTMODELNUMBER          1174
#define IDC_ROUTER                      1174
#define IDC_PRODUCTDESCRIPTION          1175
#define IDC_SEGTYPE                     1175
#define IDC_SEGBOTH                     1176
#define IDC_SEGTRANSMIT                 1177
#define IDC_SEGRECEIVE                  1178
#define IDC_RAW                         1178
#define IDC_SEGNONE                     1179
#define IDC_BTR                         1179
#define IDC_DEVICELIST                  1180
#define IDC_BBMD                        1180
#define IDC_NEWDEVICE                   1181
#define IDC_BIP                         1181
#define IDC_IAM                         1182
#define IDC_FOREIGN                     1182
#define IDC_SEGSIZE                     1183
#define ID_BBMDPEERS                    1183
#define ID_BTRPEERS                     1184
#define IDC_OBJPROP                     1184
#define IDC_DEVADV                      1184
#define IDC_HOSTADDR                    1185
#define IDC_DELETEDEVICE                1185
#define IDC_STARTDATUM                  1190
#define IDC_ENDDATUM                    1191
#define IDC_COUNT                       1192
#define IDC_REFINDEX                    1193
#define IDC_RADIONONE                   1195
#define IDC_RADIOPOSITION               1196
#define IDC_RADIOTIME                   1197
#define IDC_RADIOTIMERANGE              1198
#define IDC_RADIOSEQUENCE               1198
#define IDC_TIMESTART                   1199
#define IDC_ENDTIME                     1200
#define IDC_BEGDATECAPTION              1201
#define IDC_AUTOSYNCTIME                1202
#define IDC_DAYLIGHTSAVINGS             1203
#define IDC_UTCDATE                     1204
#define IDC_UTCTIME                     1205
#define IDC_UTCOFFSET                   1206
#define IDC_STATICUTCDATE               1207
#define IDC_STATICUTCTIME               1208
#define IDC_STATICUTCOFFSET             1209
#define IDC_STATICUTCTIMEFMT            1211
#define IDC_STATICUTCRANGE              1212
#define IDC_EDIT_LINEINDEX              1213
#define IDC_BDTPORT                     1213
#define IDC_TOTALSENT                   1213
#define IDC_TOTALSEND                   1213
#define IDC_IP                          1214
#define IDC_TOTALRECEIVE                1214
#define IDC_MASK                        1215
#define IDC_SENDRATE                    1215
#define IDC_IPSEND                      1215
#define IDC_RECEIVERATE                 1216
#define IDC_IPRECEIVE                   1216
#define IDC_ETHERNETSEND                1217
#define IDC_ALARMANDEVENT               1218
#define IDC_ETHERNETRECEIVE             1218
#define IDC_FILEACCESS                  1219
#define IDC_OBJECTACCESS                1220
#define IDC_DETAIL                      1221
#define IDC_ARCNETSEND                  1221
#define IDC_ARCNETRECEIVE               1222
#define IDC_IP_SEND                     1223
#define IDC_IP_SEND_CHECK               1223
#define IDC_MSTPSEND                    1223
#define IDC_ETHERNET_SEND               1224
#define IDC_MSTPRECEIVE                 1224
#define IDC_SERVICE_TREE                1225
#define IDC_PACKET_TYPE                 1226
#define IDC_PTPSEND                     1226
#define IDC_PTPRECEIVE                  1227
#define IDC_ARCNET_SEND                 1228
#define IDC_REMOTEDEVICEMANAGEMENT      1229
#define IDC_IP_RECEIVE_CHECK            1229
#define IDC_PACKET_TYPE_TEXT            1229
#define IDC_VIRTUALTERMINAL             1230
#define IDC_MSTP_SEND                   1230
#define IDC_ETHERNET_SEND_CHECK         1230
#define IDC_ACK                         1231
#define IDC_ETHERNET_RECEIVE_CHECK      1231
#define IDC_ERRORS                      1232
#define IDC_ARCNET_SEND_CHECK           1232
#define IDC_PTP_SEND                    1233
#define IDC_ARCNET_RECEIVE_CHECK        1233
#define IDC_OVERALL_SEND                1234
#define IDC_MSTP_SEND_CHECK             1234
#define IDC_IP_RECEIVE                  1235
#define IDC_MSTP_RECEIVE_CHECK          1235
#define IDC_ETHERNET_RECEIVE            1236
#define IDC_PTP_RECEIVE_CHECK           1236
#define IDC_ARCNET_RECEIVE              1237
#define IDC_PTP_SEND_CHECK              1237
#define IDC_MSTP_RECEIVE                1238
#define IDC_OVERALL_SEND_CHECK          1238
#define IDC_PTP_RECEIVE                 1239
#define IDC_OVERALL_RECEIVE_CHECK       1239
#define IDC_OVERALL_RECEIVE             1240
#define IDC_SEL_ALL                     1240
#define IDC_CLEAR_ALL                   1241
#define IDC_RANGE_2                     1243
#define IDC_RANGE_3                     1244
#define IDC_RANGE_4                     1245
#define IDC_RANGE_5                     1246
#define IDC_OPTIONS                     1247
#define IDC_ADDCOMP                     1248
#define IDC_BAUDRATE                    1249
#define IDC_EDIT_IUTIP                  1249
#define IDC_REMOVECOMP                  1249
#define IDC_COMPLIST                    1250
#define IDC_COMBO_NETWORK               1251
#define IDC_RPALL_NETWORK               1251
#define IDC_EPICSCONSRESULT             1252
#define IDC_SCRIPTMAKETEXT1             1253
#define IDC_DATETIME_DATE               1255
#define IDC_PACKETFILE                  1256
#define IDC_DATETIME_TIME               1256
#define IDC_DATERANGE_STARTDATE         1257
#define IDC_DEVICETREE                  1258
#define IDC_DATERANGE_ENDDATE           1258
#define IDC_CALENDARENTRY_STARTDATE     1259
#define IDC_ADDRESSBINDING_NETWORKNUMBER 1259
#define IDC_ACTIONCOMBO                 1259
#define IDC_CALENDARENTRY_ENDDATE       1260
#define IDC_ADDRESSBINDING_OBJECTID     1260
#define IDC_CALENDARENTRY_WEEKNDAY      1261
#define IDC_ADDRESSBINDING_MACADDRESS   1261
#define IDC_ADDRESSBINDING_OIDBUTTON    1263
#define IDC_CALENDARENTRY_DATERADIO     1264
#define IDC_CALENDARENTRY_DATERANGERADIO 1265
#define IDC_DEVTREEHOLDER               1266
#define IDC_CALENDARENTRY_WEEKNDAYRADIO 1266
#define IDC_CALENDARENTRY_DATE          1267
#define IDC_PROPISARRAY                 1268
#define IDC_TIMESTAMP_TIMERADIO         1268
#define IDC_TYPESHEETHOLDER             1269
#define IDC_TIMESTAMP_UNSIGNEDRADIO     1269
#define IDC_TAB1                        1270
#define IDC_TIMESTAMP_DATETIMERADIO     1270
#define IDC_BTYPEDESCRIPTOR             1271
#define IDC_TIMESTAMP_TIME              1271
#define IDC_VALUEBOOL                   1272
#define IDC_TIMESTAMP_UNSIGNED          1272
#define IDC_TIMESTAMP_DATETIME_DATE     1273
#define IDC_TIMESTAMP_DATETIME_TIME     1274
#define IDC_PORTPAGE_HOLDER             1275
#define IDC_NOETHERNET                  1279
#define IDC_PREF_PACKETCOUNT            1283
#define IDC_PREF_ASTIMEOUT              1284
#define IDC_PREF_RELATIVE               1285
#define IDC_PREF_ABSOLUTE               1286
#define IDC_PREF_DELETEVERIFY           1288
#define IDC_PREF_LOADEPICS              1289
#define IDC_VENDOR_PROPID               1289
#define IDC_INCLUDEPLACE                1290
#define IDC_INCLUDEERROR                1291
#define IDC_INCLUDEICON                 1292
#define IDC_EDIT1                       1293
#define IDC_DESTINATION_NETWORK         1293
#define IDC_MSTPMAC                     1293
#define IDC_EPICSV_FILENAME             1293
#define IDC_REALINCR                    1293
#define IDC_TIMEDELAY                   1293
#define IDC_DISCLAIMER                  1293
#define IDC_DEVICEOBJINST               1293
#define IDC_RESENDINTERVAL              1293
#define IDC_EVENTS                      1293
#define IDC_RPALL_DA                    1294
#define IDC_MSTPMAXMASTER               1294
#define IDC_PROCESS_IDENTIFIER          1294
#define ID_NEWFILTER                    1295
#define IDC_RPALL_DNET_DADR             1295
#define IDC_MSTPMAXINFO                 1295
#define ID_DELETEFILTER                 1296
#define ID_IMPORTFILTERS                1297
#define ID_EXPORTFILTERS                1298
#define IDC_FILTERLIST                  1299
#define IDC_FILTERUP                    1300
#define IDC_FILTERDOWN                  1301
#define IDC_DNETPRESENT                 1302
#define IDC_LIST_LISTOF                 1303
#define IDC_LISTOF_ADD                  1304
#define IDC_LISTOF_DELETE               1305
#define IDC_LISTOF_MODIFY               1306
#define IDC_DESTINATION_SUNDAY          1309
#define IDC_DESTINATION_MONDAY          1310
#define IDC_DESTINATION_TUESDAY         1311
#define IDC_DESTINATION_WEDNESDAY       1312
#define IDC_DESTINATION_THURSDAY        1313
#define IDC_DESTINATION_FRIDAY          1314
#define IDC_DESTINATION_SATURDAY        1315
#define IDC_DESTINATION_OFFNORMAL       1318
#define IDC_DESTINATION_FAULT           1319
#define IDC_DESTINATION_NORMAL          1320
#define IDC_DESTINATION_CONFIRM         1321
#define IDC_DESTINATION_ADDRESS         1322
#define IDC_DESTINATION__MACADDRESS     1323
#define IDC_DESTINATION_DEVICE          1324
#define IDC_DESTINATION_DEVICEID        1327
#define IDC_DESTINATION_DEVICEIDBTN     1329
#define IDC_COMBO_ITEMTYPE              1330
#define IDC_REINITSTATE                 1330
#define IDC_DESTINATION_FROMTIME        1332
#define IDC_DESTINATION_TOTIME          1333
#define IDC_NBLINKSOCKET                1335
#define ID_NBLINKPARMS                  1336
#define ID_MSTPCONFIGIMP                1336
#define IDC_NBLINKLOCALPORT             1336
#define IDC_MSTPFRTYPECOMBO             1337
#define IDC_NBLINKRESETLOCALPORT        1337
#define IDC_MSTPBAUD                    1338
#define IDC_MSTPIMP                     1339
#define IDC_NBLINKADDR                  1340
#define IDC_NBLINKSUBNETMASK            1341
#define IDC_NBLINKRESETADDR             1342
#define IDC_NBLINKRESET                 1343
#define IDC_NBLINKSTARTUP               1344
#define IDC_NBLINKGATEWAY               1345
#define IDC_EPICSV_LOAD                 1345
#define IDC_EPICSV_RESET                1346
#define IDC_EPICSV_INFO                 1347
#define IDC_TREE1                       1348
#define IDC_EPICSV_TREE                 1348
#define IDC_EPICSV_EDIT                 1349
#define IDC_EPICSV_GEN                  1350
#define IDC_EPICSV_GENALL               1351
#define IDC_PRENOTIF                    1354
#define IDC_CURNOTIF                    1355
#define IDC_HASOBJID                    1358
#define IDC_EVENTINFOLIST               1360
#define IDC_SETTIMESTAMP                1361
#define IDC_SETPRIORITIES               1362
#define IDC_OFFNORMAL                   1363
#define IDC_OFFNORMAL1                  1369
#define IDC_FAULT1                      1370
#define IDC_NORMAL1                     1371
#define IDC_TIMESTAMPLIST               1373
#define IDC_UNSIGNEDLIST                1374
#define IDC_TIMERADIO                   1375
#define IDC_UNSIGNEDRADIO               1376
#define IDC_DATETIMERADIO               1377
#define IDC_MOREEVENT                   1379
#define IDC_QUITONFAIL                  1383
#define IDC_WRITESUCCESS                1384
#define IDC_BINARYPVCOMBO               1385
#define IDC_REALVALUE                   1386
#define IDC_NULLVALUE                   1387
#define IDC_DOFWEEK_MONDAY              1388
#define IDC_TIMECHANGE                  1388
#define IDC_DOFWEEK_TUESDAY             1389
#define IDC_DOFWEEK_WEDNESDAY           1390
#define IDC_DOFWEEK_THURSDAY            1391
#define IDC_DOFWEEK_FRIDAY              1392
#define IDC_DOFWEEK_SATURDAY            1393
#define IDC_DOFWEEK_SUNDAY              1394
#define IDC_ENUMRATECOMBO               1395
#define IDC_RADIODEVICE                 1396
#define IDC_WEEKOFMONTH                 1396
#define IDC_RADIOADDRESS                1397
#define IDC_DAYOFWEEK                   1397
#define IDC_ISSUECFMNTF                 1398
#define IDC_TIMEREMAIN                  1399
#define IDC_INCREMENT                   1400
#define IDC_LOGDISABLED                 1401
#define IDC_BUFFERPURGED                1402
#define IDC_MONTH                       1403
#define IDC_FIRSTITEM                   1404
#define IDC_LASTITEM                    1405
#define IDC_CHOICE                      1409
#define IDC_ONVALUE                     1410
#define IDC_BOOLVALUE                   1411
#define IDC_UNSIGNEDVALUE               1412
#define IDC_RADIONULL                   1413
#define IDC_RADIOBINARY                 1415
#define IDC_RADIOINTEGER                1416
#define IDC_RADIOVALUE                  1417
#define IDC_RADIOREAL                   1418
#define IDC_BINARYPV                    1419
#define IDC_ANYVALUE                    1420
#define IDC_LOGDATUM                    1421
#define IDC_ERRORCLASS                  1422
#define IDC_ERRORCODE                   1423
#define IDC_ENUMVALUE                   1425
#define IDC_INTERGERVALUE               1427
#define IDC_BITSTRINGVALUE              1428
#define IDC_HASSTATUSFLAGS              1432
#define IDC_AICHECK                     1433
#define IDC_AOCHECK                     1434
#define IDC_EVCHECK                     1435
#define IDC_AVCHECK                     1436
#define IDC_DECHECK                     1437
#define IDC_AVGCHECK                    1438
#define IDC_BICHECK                     1439
#define IDC_COCHECK                     1440
#define IDC_BOCHECK                     1441
#define IDC_BVCHECK                     1442
#define IDC_CACHECK                     1443
#define IDC_SELECTALL                   1445
#define IDC_FICHECK                     1446
#define IDC_GRCHECK                     1447
#define IDC_SCCHECK                     1448
#define IDC_LOCHECK                     1449
#define IDC_PRCHECK                     1450
#define IDC_LSPCHECK                    1451
#define IDC_LSZCHECK                    1452
#define IDC_NTCHECK                     1453
#define IDC_MSICHECK                    1454
#define IDC_MSOCHECK                    1455
#define IDC_MSVCHECK                    1456
#define IDC_TRCHECK                     1457
#define IDC_DEVCOMCTRL                  1458
#define IDC_ACKALARM                    1459
#define IDC_CFMCOVN                     1460
#define IDC_CFMEVN                      1461
#define IDC_GETALARMSUM                 1462
#define IDC_GETENRSUM                   1463
#define IDC_WRITEPROPM                  1464
#define IDC_LFSFTYO                     1465
#define IDC_GETEVNINFO                  1466
#define IDC_SUBSCOV                     1467
#define IDC_SUBSCOBPROP                 1468
#define IDC_ADDLIST                     1469
#define IDC_RMLIST                      1470
#define IDC_CREATOBJ                    1471
#define IDC_DELOBJ                      1472
#define IDC_READPROP                    1473
#define IDC_READPROPC                   1474
#define IDC_READPROPM                   1475
#define IDC_VTCLOSE                     1476
#define IDC_VTOPEN                      1477
#define IDC_VTDATA                      1478
#define IDC_AWRITEFILE                  1479
#define IDC_AREADFILE                   1480
#define IDC_REQUESTKEY                  1481
#define IDC_AUTHEN                      1482
#define IDC_TIMESYN                     1483
#define IDC_UCFMTEXTMSG                 1485
#define IDC_UCFMPRVTR                   1487
#define IDC_UCFMEVEN                    1488
#define IDC_IHAVE                       1489
#define IDC_UCFMCOVN                    1490
#define IDC_UTCTIMESYN                  1491
#define IDC_WHOHAS                      1492
#define IDC_READRANGE                   1493
#define IDC_WRITEPROP                   1494
#define IDC_WHOIS                       1495
#define IDC_CFMPRVTRANS                 1496
#define IDC_CFMTEXTMSG                  1497
#define IDC_REINITDEV                   1498
#define IDC_LISTOFTIMEVALUES            1500
#define IDC_RADIOCALENTRY               1502
#define IDC_RADIOOBJID                  1503
#define IDC_BITSTRING                   1505
#define IDC_BITSTRINGLIST               1506
#define IDC_ENUMLIST                    1508
#define IDC_BITMASK                     1510
#define IDC_LISTOFBSTR                  1511
#define IDC_NTFTHRESH                   1512
#define IDC_LISTOFAV                    1512
#define IDC_PREVIOUSNOTFC               1513
#define IDC_LISTOFLSFAV                 1515
#define IDC_LISTOFPROPSTATES            1516
#define IDC_RADIOBITSTR                 1517
#define IDC_EPICSV_PROP_LIST            1521
#define IDC_EPICSV_DA                   1522
#define IDC_ALLBACKUPRESTORE            1523
#define IDC_BACKUP_RESTORE_OUTPUT       1523
#define IDC_DOW3                        1523
#define IDC_DOW2                        1524
#define IDC_FULLBACKUPRESTORE           1524
#define IDC_BACKUP_RESTORE_KILL         1524
#define IDC_DOW1                        1525
#define IDC_RESTOREONLY                 1525
#define IDC_DOW4                        1526
#define IDC_AUXILIARYBACKUPRESTORE      1526
#define IDC_BACKUPONLY                  1527
#define IDC_COMBOBOXEX1                 1527
#define IDC_COLORCOMBO1                 1527
#define IDC_BACKUPFILENAME              1528
#define IDC_AUTOSCROLL                  1528
#define IDC_ALLTESTS                    1528
#define IDC_RECVPKT                     1529
#define IDC_BACKUPFILENAME2             1530
#define IDC_SAVESENTPKT                 1530
#define IDC_BROWSE                      1531
#define IDC_DESCOMBO                    1531
#define IDC_COMBOBOXEX2                 1532
#define IDC_COLORCOMBO2                 1532
#define IDC_COMBOBOXEX3                 1533
#define IDC_COLORCOMBO3                 1533
#define IDC_COMBOBOXEX4                 1534
#define IDC_COLORCOMBO4                 1534
#define IDC_COMBOBOXEX5                 1535
#define IDC_COLORCOMBO6                 1535
#define IDC_SNETCHECK                   1535
#define IDC_COLORCOMBO5                 1536
#define IDC_DNETCHECK                   1536
#define IDC_DELAY                       1543
#define IDC_BACKUPTIMEOUT               1544
#define IDC_INTERFACE                   1550
#define IDC_EVENTTYPE                   1551
#define IDC_EXVALUE                     1552
#define IDC_RADIO1                      1552
#define IDC_EXLIMIT                     1553
#define IDC_RADIO2                      1553
#define IDC_LS_STATE                    1553
#define IDC_CHECK4                      1554
#define IDC_RICHEDIT1                   1554
#define IDC_CHECK5                      1555
#define IDC_SASUM                       1555
#define IDC_CHECK6                      1556
#define IDC_SESUM                       1556
#define IDC_INVALIDTAG                  1556
#define IDC_CHECK7                      1557
#define IDC_SINFO                       1557
#define IDC_MISSINGREQPAR               1557
#define IDC_CHECK8                      1558
#define IDC_TOOMANYARGS                 1558
#define IDC_CHECK9                      1559
#define IDC_CHECK10                     1560
#define IDC_LIST1                       1560
#define IDC_CHECK11                     1561
#define IDC_CHECK12                     1562
#define IDC_CHECK13                     1563
#define IDC_CHECK14                     1564
#define IDC_CHECK15                     1565
#define IDC_CHECK16                     1566
#define IDC_CHECK17                     1567
#define IDC_CHECK18                     1568
#define IDC_CHECK19                     1569
#define IDC_CHECK20                     1570
#define IDC_CHECK21                     1571
#define IDC_CHECK22                     1572
#define IDC_CHECK23                     1573
#define IDC_CHECK24                     1574
#define IDC_CHECK25                     1575
#define IDC_STATIC1                     1576
#define ID_VIEW_FIRSTFRAME              32771
#define ID_VIEW_PREVFRAME               32772
#define ID_VIEW_NEXTFRAME               32773
#define ID_VIEW_LASTFRAME               32774
#define ID_EDIT_PORTS                   32782
#define ID_EDIT_NAMES                   32783
#define ID_EDIT_CAPTUREFILTER           32785
#define ID_EDIT_DISPLAYFILTER           32786
#define ID_EDIT_PREFERENCES             32787
#define ID_EDIT_DELETE                  32788
#define ID_SCRIPT_CHECK_SYNTAX          32789
#define ID_SCRIPT_RUN                   32790
#define ID_SCRIPT_HALT                  32791
#define ID_SCRIPT_STEP                  32792
#define ID_SCRIPT_RESET                 32793
#define ID_SCRIPT_KILL                  32794
#define ID_SCRIPT_STEPPASS              32795
#define ID_SCRIPT_STEPFAIL              32796
#define ID_SEND_NEWPACKET               32797
#define ID_SEND_SENDAGAIN               32798
#define ID_BUTTON32799                  32799
#define ID_BUTTON32800                  32800
#define ID_EPICS_LOAD                   32801
#define ID_EPICS_LOADAUTO               32802
#define ID_EDIT_DEVICES                 32803
#define IDC_EDIT_GOTOLINE               32804
#define ID_MENUITEM32806                32806
#define ID_VIEW_HEX                     32807
#define ID_VIEW_DETAIL                  32808
#define ID_VIEW_STATISTICS              32809
#define ID_FILE_EXPORT                  32810
#define ID_SCRIPT_ENV                   32811
#define ID_EPICS_READALLPROPERTY        32812
#define ID_FILE_WKS_NEW                 32814
#define ID_FILE_WKS_OPEN                32815
#define ID_FILE_WKS_SWITCH              32816
#define ID_FILE_WKS_SAVEAS              32817
#define ID_NEWDEVICE                    32822
#define ID_NEWPROPERTY                  32823
#define ID_NEWOBJECT                    32824
#define ID_NEWVALUE                     32825
#define ID_DELETE                       32826
#define ID_NEWCOMPONENT                 32827
#define ID_EDIT_REFRESH                 32828
#define ID_SCRIPT_RUN1                  32829
#define ID_SCRIPT_CHECK_SYNTAX1         32830
#define ID_VIEW_EPICS                   32831
#define ID_BACKUP_RESTORE               32832
#define ID_EPICS_PROP_RP                32833
#define ID_EPICS_PROP_WP                32834
#define ID_EPICS_PROP_RPM               32835
#define ID_EPICS_PROP_WPM               32836
#define ID_EPICS_PROP_GEN               32837
#define ID_EPICS_PROP_CLEAR             32838
#define ID_EPICS_PROP_REUSE             32839
#define ID_VIEW_COLOR                   32839
#define ID_SAVEPKT                      32840
#define ID_PKT_FILENAME                 32841
#define ID_GLOBAL_SCRIPT_CHECKSYNTAX    32849
#define ID_FILE_MRU_WKSFIRST            32850
#define ID_FILE_MRU_WKS1                32850
#define ID_GLOBAL_SCRIPT_RESET          32850
#define ID_FILE_MRU_WKS2                32851
#define ID_GLOBAL_SCRIPT_RUN            32851
#define ID_FILE_MRU_WKS3                32852
#define ID_GLOBAL_SCRIPT_HALT           32852
#define ID_FILE_MRU_WKS4                32853
#define ID_GLOBAL_SCRIPT_STEP           32853
#define ID_FILE_MRU_WKS5                32854
#define ID_GLOBAL_SCRIPT_STEPPASS       32854
#define ID_FILE_MRU_WKS6                32855
#define ID_GLOBAL_SCRIPT_STEPFAIL       32855
#define ID_FILE_MRU_WKS7                32856
#define ID_GLOBAL_SCRIPT_KILL           32856
#define ID_FILE_MRU_WKS8                32857
#define ID_GLOBAL_NEW_LOGFILE           32857
#define ID_FILE_MRU_WKS9                32858
#define ID_GLOBAL_DISABLE_PORT          32858
#define ID_FILE_MRU_WKS10               32859
#define ID_FILE_MRU_WKS11               32860
#define ID_FILE_MRU_WKS12               32861
#define ID_VIEW_GLOBALBAR               32861
#define ID_FILE_MRU_WKS13               32862
#define ID_VIEW_MAINTOOLBAR             32862
#define ID_FILE_MRU_WKS14               32863
#define ID_VIEW_GLOBAL_TOOLBAR          32863
#define ID_FILE_MRU_WKS15               32864
#define ID_FILE_MRU_WKSLAST             32864
#define ID_TESTS_INCONSISTENTPARS       32866
#define ID_FIND_FINDNEXT                32868
#define ID_EDIT_DELETESEL               32870
#define ID_EDIT_SENDPACKET              32871
#define ID_COMBOBOX_SEPARATOR           32873
#define ID_EDIT_QUICKSAVE               32874
#define ID_EDIT_AUTOSCROLL              32875
#define ID_SET_TEMPLATE_FILE            32877
#define ID_SCRIPT_TEMPLATE_0            32878
#define ID_SCRIPT_TEMPLATE_10           32888
#define ID_SCRIPT_TEMPLATE_20           32898
#define ID_SCRIPT_TEMPLATE_29           32907
#define ID_EDIT_LOGFILE                 32908
#define ID_EDIT_AUTO_OBJECT             32909
#define ID_EDIT_AUTO_PROPERTY           32910
#define IDS_BTYPE0                      32950
#define IDS_BTYPE1                      32951
#define IDS_BTYPE2                      32952
#define IDS_BTYPE3                      32953
#define IDS_BTYPE4                      32954
#define IDS_BTYPE5                      32955
#define IDS_BTYPE6                      32956
#define IDS_BTYPE7                      32957
#define IDS_BTYPE8                      32958
#define IDS_BTYPE9                      32959
#define IDS_BTYPE10                     32960
#define IDS_BTYPE11                     32961
#define IDS_BTYPE12                     32962
#define IDS_BTYPE13                     32963
#define IDS_BTYPE14                     32964
#define IDS_SCREX_COMPREAL              33000
#define IDS_SCREX_COMPEPICSNULL         33001
#define IDS_SCREX_COMPREALDATALEN       33002
#define IDS_SCREX_COMPDATANULL          33003
#define IDS_SCREX_COMPINT               33004
#define IDS_SCREX_COMPUINT              33005
#define IDS_SCREX_COMPARRAY             33006
#define IDS_SCREX_COMPSHORTDATA         33007
#define IDS_SCREX_COMPSTREAMFAIL_NE     33008
#define IDS_SCREX_COMPSTREAM_E          33009
#define IDS_SCREX_COMPEQREQ             33010
#define IDS_SCREX_COMPSTRING            33012
#define IDS_SCREX_COMPFAILTYPE          33013
#define IDS_SCREX_COMPARRAYSIZE         33014
#define IDS_SCREX_COMPARRAYINXBOUNDS    33015
#define IDS_SCREX_COMPUNSUPPORTED       33016
#define IDS_SCREX_COMPFAIL              33017
#define IDS_SCREX_COMPFAILBITSTRING     33018
#define IDS_SCREX_COMPFAILENUM          33019
#define IDS_SCREX_COMPFAILPROP          33020
#define IDS_SCREX_COMPFAILDEVID         33021
#define IDS_SCREX_COMPFAILOBJID         33022
#define IDS_SCREX_COMPFAILSTRING        33023
#define IDS_SCREX_COMPFAILOCTSTRING     33024
#define IDS_SCREX_COMPFAILDOUBLE        33025
#define IDS_SCREX_COMPFAILREAL          33026
#define IDS_SCREX_COMPFAILINT           33027
#define IDS_SCREX_COMPFAILUNSIGNED      33028
#define IDS_SCREX_COMPFAILBOOL          33029
#define IDS_SCREX_COMPFAILSTRENCODING   33030
#define IDS_SCREX_COMPFAILDATE          33031
#define IDS_SCREX_COMPFAILTIME          33032
#define IDS_SCREX_INDEXUNSEXP           33033
#define IDS_SCREX_INDEXBOUNDS           33034
#define IDS_SCREX_INDEXUNSVAR           33035
#define IDS_SCREX_ASGN_UNDEFVAR         33036
#define IDS_SCREX_BADDATADATE           33037
#define IDS_SCREX_BADDATATIME           33038
#define IDS_SCREX_COMPFAILANY           33039
#define IDS_ERR_FILEPKTOPEN             34000
#define IDS_DEVTREE_CAPTION             34001
#define IDS_ERR_FILENOTPKT              34002
#define IDS_ERR_FILEMOVEON              34003
#define IDS_ERR_FILEOPENRCT             34004
#define IDS_ERR_FILEPKTRELOAD           34005
#define IDS_NEWPACKETFILENAME           34006
#define IDS_ERR_MAXPACKETS              34007
#define IDS_ERR_NOREALDEVICENAME        34008
#define IDS_ERR_TASKERROR               34009
#define ID_SW_NO                        45841
#define ID_SW_TIMESTAMP                 45842
#define ID_SW_PORT                      45843
#define ID_SW_SOURCE                    45844
#define ID_SW_DES                       45845
#define ID_SW_SNET                      45846
#define ID_SW_SADDR                     45847
#define ID_SW_DNET                      45848
#define ID_SW_DADDR                     45849
#define ID_SW_SERVICE                   45850
#define ID_EDIT_RECEIVEPKT              45900
#define ID_EDIT_SAVESENTPKT             45901
#define ID_EDIT_COLUMNVALUE             45902
#define ID_EDIT_SENDALLPACKET           45903
#define ID_EDIT_EDITSENDALLPKT          45904
#define IDS_WKS_SWITCH                  57346
#define IDS_WKS_OVERWRITE               57347
#define IDS_WKS_OVERWRITESAVE           57348
#define IDS_DELETEAREYOUSURE            57349
#define IDS_REGISTRYKEY                 57350
#define IDS_NAME_ADDRERROR              57682
#define IDS_FILTER_ADDRERROR            57683

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        383
#define _APS_NEXT_COMMAND_VALUE         32912
#define _APS_NEXT_CONTROL_VALUE         1577
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
